ascoders/weekly

- 12.精读 React 高阶组件.md
> Update 12.精读 React 高阶组件.md

- 48.精读《Immer.js》源码.md
> fix  精读《Immer.js》源码.md修改错别字

- 53.精读《插件化思维》.md
fix： 时间 -> 事件
style： 必要英文词汇加入 `` md code标识
> 修改错别字，md样式问题

- 79.精读《React Hooks》.md
> Update 79.精读《React Hooks》.md

- 105.精读《What's new in javascript》.md
> Update 105.精读《What's new in javascript》.md

- 64.精读《手写 SQL 编译器 - 词法分析》.md
> Update 64.精读《手写 SQL 编译器 - 词法分析》.md

- 107.精读《Optional chaining》.md
> Update 107.精读《Optional chaining》.md

- 064.精读《手写 SQL 编译器 - 词法分析》.md
> Update 064.精读《手写 SQL 编译器 - 词法分析》.md

- 082.精读《Htm - Hyperscript 源码》.md
> Update 082.精读《Htm - Hyperscript 源码》.md

- 113.精读《Nodejs V12》.md
> Update 113.精读《Nodejs V12》.md

- 092.精读《React PowerPlug 源码》.md
> Update 092.精读《React PowerPlug 源码》.md

- 104.精读《Function Component 入门》.md
> Update 104.精读《Function Component 入门》.md

- 128.精读《Hooks 取数 - swr 源码》.md
源码中批量更新策略已从unstable_batchedUpdates换为useReducer
> fix: update

- 145.精读《React Router v6》.md
> Update 145.精读《React Router v6》.md

- 148. 精读《React Error Boundaries》.md
> Update 148. 精读《React Error Boundaries》.md

- 163.精读《Spring 概念》.md
> Update 163.精读《Spring 概念》.md

- 171.精读《设计模式 - Singleton 单例模式》.md
class method: `instance` -> `getInstance`
> Update 171.精读《设计模式 - Singleton 单例模式》.md

- 前沿技术/196.精读《前端职业规划 - 2021 年》.md
Signed-off-by: Jie Peng <im@jiepeng.me>
> fix(196): typo

- 前沿技术/41.精读《Ant Design 3.0 背后的故事》.md
> Update 41.精读《Ant Design 3.0 背后的故事》.md

- 前沿技术/140.精读《结合 React 使用原生 Drag Drop API》.md
> Update 140.精读《结合 React 使用原生 Drag Drop API》.md

- 设计模式/186.精读《设计模式 - State 状态模式》.md
Provides a more comprehensive and work example
> Update 186.精读《设计模式 - State 状态模式》.md

- 前沿技术/72.精读《REST, GraphQL, Webhooks, & gRPC 如何选型》.md
> Update 72.精读《REST, GraphQL, Webhooks, & gRPC 如何选型》.md

- 设计模式/167.精读《设计模式 - Abstract Factory 抽象工厂》.md
> fix: spelling mistake in 167

- 前沿技术/95.精读《Function VS Class 组件》.md
> Update 95.精读《Function VS Class 组件》.md
